const skillChoices = {
  barbarian: [
    'Atletismo',
    'Intimidación',
    'Naturaleza',
    'Percepción',
    'Supervivencia',
    'Trato con Animales',
  ],
  bard: [
    'Acrobacias',
    'Arcanos',
    'Atletismo',
    'Engaño',
    'Historia',
    'Interpretación',
    'Intimidación',
    'Investigación',
    'Juego de Manos',
    'Medicina',
    'Naturaleza',
    'Percepción',
    'Perspicacia',
    'Persuasión',
    'Religión',
    'Sigilo',
    'Supervivencia',
    'Trato con Animales',
  ],
  cleric: [
    'Historia',
    'Intimidación',
    'Medicina',
    'Perspicacia',
    'Persuasión',
    'Religión',
  ],
  druid: [
    'Arcanos',
    'Medicina',
    'Naturaleza',
    'Percepción',
    'Religión',
    'Supervivencia',
    'Trato con Animales',
  ],
  fighter: [
    'Acrobacias',
    'Atletismo',
    'Historia',
    'Intimidación',
    'Percepción',
    'Perspicacia',
    'Supervivencia',
    'Trato con Animales',
  ],
  monk: [
    'Acrobacias',
    'Atletismo',
    'Historia',
    'Perspicacia',
    'Religión',
    'Sigilo',
  ],
  paladin: [
    'Atletismo',
    'Intimidación',
    'Medicina',
    'Perspicacia',
    'Persuasión',
    'Religión',
  ],
  ranger: [
    'Atletismo',
    'Investigación',
    'Naturaleza',
    'Percepción',
    'Sigilo',
    'Supervivencia',
    'Trato con Animales',
  ],
  rogue: [
    'Acrobacias',
    'Atletismo',
    'Engaño',
    'Interpretación',
    'Intimidación',
    'Investigación',
    'Juego de Manos',
    'Percepción',
    'Perspicacia',
    'Persuasión',
    'Sigilo',
  ],
  sorcerer: [
    'Arcanos',
    'Engaño',
    'Intimidación',
    'Perspicacia',
    'Persuasión',
    'Religión',
  ],
  warlock: [
    'Arcanos',
    'Engaño',
    'Historia',
    'Intimidación',
    'Investigación',
    'Naturaleza',
    'Religión',
  ],
  wizard: [
    'Arcanos',
    'Historia',
    'Investigación',
    'Medicina',
    'Perspicacia',
    'Religión',
  ],
};

const equipmentChoices: Record<string, { label: string; options: string[] }[]> = {
  barbaro: [
    { label: 'Arma principal', options: ['Gran hacha', 'Cualquier arma marcial cuerpo a cuerpo'] },
    { label: 'Arma secundaria', options: ['Dos hachas de mano', 'Cualquier arma simple'] },
    { label: 'Equipo', options: ['Equipo de explorador'] },
    { label: 'Munición', options: ['Cuatro jabalinas'] },
  ],
  bardo: [
    { label: 'Arma', options: ['Estoque', 'Espada larga', 'Cualquier arma simple'] },
    { label: 'Equipo', options: ['Equipo diplomático', 'Equipo de artista'] },
    { label: 'Instrumento', options: ['Laúd', 'Otro instrumento musical'] },
    { label: 'Protección', options: ['Armadura de cuero'] },
    { label: 'Arma ligera', options: ['Daga'] },
  ],
  clerigo: [
    { label: 'Arma', options: ['Maza', 'Martillo de guerra'] },
    { label: 'Armadura', options: ['Armadura de escamas', 'Armadura de cuero', 'Cota de malla si tienes competencia'] },
    { label: 'Arma a distancia', options: ['Ballesta ligera y 20 virotes', 'Cualquier arma simple'] },
    { label: 'Equipo', options: ['Equipo de sacerdote', 'Equipo de explorador'] },
    { label: 'Foco', options: ['Símbolo sagrado'] },
  ],
  druida: [
    { label: 'Defensa', options: ['Escudo de madera', 'Cualquier arma simple'] },
    { label: 'Arma', options: ['Cimitarra', 'Cualquier arma cuerpo a cuerpo simple'] },
    { label: 'Armadura', options: ['Armadura de cuero'] },
    { label: 'Equipo', options: ['Equipo de explorador'] },
    { label: 'Foco', options: ['Foco druídico'] },
  ],
  guerrero: [
    { label: 'Armadura', options: ['Cota de malla', 'Armadura de cuero, arco largo y 20 flechas'] },
    { label: 'Armas', options: ['Arma marcial y escudo', 'Dos armas marciales'] },
    { label: 'Arma secundaria', options: ['Ballesta ligera y 20 virotes', 'Dos hachas de mano'] },
    { label: 'Equipo', options: ['Equipo de explorador', 'Equipo de aventurero'] },
  ],
  monje: [
    { label: 'Arma', options: ['Espada corta', 'Cualquier arma simple'] },
    { label: 'Equipo', options: ['Equipo de explorador', 'Equipo de aventurero'] },
    { label: 'Munición', options: ['10 dardos'] },
  ],
  paladin: [
    { label: 'Armas', options: ['Arma marcial y escudo', 'Dos armas marciales'] },
    { label: 'Arma secundaria', options: ['Cinco jabalinas', 'Cualquier arma simple'] },
    { label: 'Equipo', options: ['Equipo de sacerdote', 'Equipo de explorador'] },
    { label: 'Armadura', options: ['Cota de malla'] },
    { label: 'Foco', options: ['Símbolo sagrado'] },
  ],
  explorador: [
    { label: 'Armadura', options: ['Armadura de escamas', 'Armadura de cuero'] },
    { label: 'Armas cuerpo a cuerpo', options: ['Dos espadas cortas', 'Dos armas simples'] },
    { label: 'Equipo', options: ['Equipo de explorador', 'Equipo de aventurero'] },
    { label: 'Arma a distancia', options: ['Arco largo y carcaj con 20 flechas'] },
  ],
  picaro: [
    { label: 'Arma principal', options: ['Estoque', 'Espada corta'] },
    { label: 'Arma secundaria', options: ['Arco corto y carcaj con 20 flechas', 'Espada corta'] },
    { label: 'Equipo', options: ['Equipo de ladrón', 'Equipo de aventurero', 'Equipo de explorador'] },
    { label: 'Armadura', options: ['Armadura de cuero'] },
    { label: 'Armas ligeras', options: ['Dos dagas'] },
    { label: 'Herramientas', options: ['Herramientas de ladrón'] },
  ],
  hechicero: [
    { label: 'Arma', options: ['Ballesta ligera y 20 virotes', 'Cualquier arma simple'] },
    { label: 'Foco', options: ['Bolsa de componentes', 'Foco arcano'] },
    { label: 'Equipo', options: ['Equipo de explorador', 'Equipo de aventurero'] },
    { label: 'Armas ligeras', options: ['Dos dagas'] },
  ],
  brujo: [
    { label: 'Arma', options: ['Ballesta ligera y 20 virotes', 'Cualquier arma simple'] },
    { label: 'Foco', options: ['Bolsa de componentes', 'Foco arcano'] },
    { label: 'Equipo', options: ['Equipo de erudito', 'Equipo de aventurero'] },
    { label: 'Armadura', options: ['Armadura de cuero'] },
    { label: 'Arma simple', options: ['Cualquier arma simple'] },
    { label: 'Armas ligeras', options: ['Dos dagas'] },
  ],
  mago: [
    { label: 'Arma', options: ['Bastón', 'Daga'] },
    { label: 'Foco', options: ['Bolsa de componentes', 'Foco arcano'] },
    { label: 'Equipo', options: ['Equipo de erudito', 'Equipo de explorador'] },
    { label: 'Libro', options: ['Libro de conjuros'] },
  ],
};

const rawClassesSeed = [
  {
    name: 'Bárbaro',
    slug: 'barbaro',
    description:
      'Guerrero impulsado por una furia primitiva, duro de derribar y brutal en combate cuerpo a cuerpo.',
    hitDice: '1d12',
    primaryAbilities: ['strength', 'constitution'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['strength', 'constitution'],
      skillChoices: skillChoices.barbarian,
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Gran hacha o arma marcial cuerpo a cuerpo',
      'Dos hachas de mano o arma simple',
      'Equipo de explorador',
      'Cuatro jabalinas',
    ],
    featuresByLevel: [
      { level: 1, name: 'Furia', description: 'En combate puedes entrar en un estado de violencia concentrada.' },
      { level: 1, name: 'Defensa sin armadura', description: 'Puedes protegerte con instinto y resistencia física.' },
      { level: 2, name: 'Ataque temerario', description: 'Puedes atacar con ventaja aceptando quedar más expuesto.' },
      { level: 2, name: 'Sentido del peligro', description: 'Tus reflejos reaccionan ante amenazas visibles.' },
      { level: 3, name: 'Senda primitiva', description: 'Eliges la expresión concreta de tu furia.' },
    ],
    subclassSelectionLabel: 'Senda primitiva',
    subclassLevel: 3,
    subclasses: [
      {
        name: 'Senda del Berserker',
        slug: 'senda-del-berserker',
        description: 'Canaliza la furia como violencia desatada y resistencia mental.',
        featuresByLevel: [
          { level: 3, name: 'Frenesí', description: 'Tu furia puede volverse más agresiva a cambio de agotarte.' },
          { level: 6, name: 'Furia inconsciente', description: 'La furia te ayuda contra miedo y encantamiento.' },
          { level: 10, name: 'Presencia intimidante', description: 'Puedes quebrar la voluntad de un enemigo.' },
        ],
        imageUrl: null,
      },
      {
        name: 'Senda del Guerrero Totémico',
        slug: 'senda-del-guerrero-totemico',
        description: 'Une furia y espiritualidad animal para ganar dones totémicos.',
        featuresByLevel: [
          { level: 3, name: 'Buscador espiritual', description: 'Tu vínculo totémico te concede magia ritual menor.' },
          { level: 3, name: 'Espíritu totémico', description: 'Eliges un espíritu que moldea tu furia.' },
          { level: 6, name: 'Aspecto de la bestia', description: 'Tu tótem influye en tus sentidos y capacidades.' },
        ],
        imageUrl: null,
      },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },
  {
    name: 'Bardo',
    slug: 'bardo',
    description:
      'Artista, narrador y lanzador de conjuros versátil que convierte talento y palabra en poder.',
    hitDice: '1d8',
    primaryAbilities: ['charisma'],
    proficiencies: {
      armor: ['Armadura ligera'],
      weapons: ['Armas simples', 'Ballesta de mano', 'Espada larga', 'Estoque', 'Espada corta'],
      tools: ['Tres instrumentos musicales'],
      savingThrows: ['dexterity', 'charisma'],
      skillChoices: skillChoices.bard,
      numberOfSkillChoices: 3,
    },
    startingEquipment: ['Estoque, espada larga o arma simple', 'Equipo diplomático o de artista', 'Laúd u otro instrumento', 'Armadura de cuero y daga'],
    featuresByLevel: [
      { level: 1, name: 'Lanzamiento de conjuros', description: 'Usas Carisma para lanzar magia barda.' },
      { level: 1, name: 'Inspiración bárdica', description: 'Puedes impulsar las tiradas de tus aliados.' },
      { level: 2, name: 'Aprendiz de todo', description: 'Tu amplitud de saber ayuda en muchas pruebas.' },
      { level: 2, name: 'Canción de descanso', description: 'Tus descansos ayudan a recuperar mejor.' },
      { level: 3, name: 'Colegio bárdico', description: 'Eliges una tradición artística y mágica.' },
    ],
    subclassSelectionLabel: 'Colegio bárdico',
    subclassLevel: 3,
    subclasses: [
      {
        name: 'Colegio del Conocimiento',
        slug: 'colegio-del-conocimiento',
        description: 'Prioriza saberes, secretos, habilidades y magia robada de otras tradiciones.',
        featuresByLevel: [
          { level: 3, name: 'Competencias adicionales', description: 'Amplías tu abanico de habilidades.' },
          { level: 3, name: 'Palabras cortantes', description: 'Tu ingenio puede entorpecer a enemigos.' },
          { level: 6, name: 'Secretos mágicos adicionales', description: 'Aprendes conjuros de otras listas antes de tiempo.' },
        ],
        imageUrl: null,
      },
      {
        name: 'Colegio del Valor',
        slug: 'colegio-del-valor',
        description: 'Une espectáculo, inspiración y entrenamiento marcial.',
        featuresByLevel: [
          { level: 3, name: 'Competencias adicionales', description: 'Ganas entrenamiento con mejores armas y armaduras.' },
          { level: 3, name: 'Inspiración de combate', description: 'Tu inspiración también potencia daño o defensa.' },
          { level: 6, name: 'Ataque adicional', description: 'Puedes atacar más veces al tomar la acción de atacar.' },
        ],
        imageUrl: null,
      },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },
  {
    name: 'Clérigo',
    slug: 'clerigo',
    description: 'Servidor de un poder divino que combina magia sagrada, convicción y apoyo en combate.',
    hitDice: '1d8',
    primaryAbilities: ['wisdom'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Armas simples'],
      tools: [],
      savingThrows: ['wisdom', 'charisma'],
      skillChoices: skillChoices.cleric,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Maza o martillo de guerra', 'Armadura de escamas, cuero o cota de malla si procede', 'Ballesta ligera o arma simple', 'Símbolo sagrado'],
    featuresByLevel: [
      { level: 1, name: 'Lanzamiento de conjuros', description: 'Usas Sabiduría para canalizar magia divina.' },
      { level: 1, name: 'Dominio divino', description: 'Tu deidad te concede un dominio y poderes asociados.' },
      { level: 2, name: 'Canalizar divinidad', description: 'Puedes liberar energía divina para efectos especiales.' },
      { level: 5, name: 'Destruir muertos vivientes', description: 'Tu canalización puede acabar con no muertos débiles.' },
    ],
    subclassSelectionLabel: 'Dominio divino',
    subclassLevel: 1,
    subclasses: [
      { name: 'Dominio del Conocimiento', slug: 'dominio-del-conocimiento', description: 'Revela secretos, lenguas y saberes ocultos.', featuresByLevel: [{ level: 1, name: 'Bendiciones del conocimiento', description: 'Obtienes idiomas y especialización en saberes.' }], imageUrl: null },
      { name: 'Dominio de la Vida', slug: 'dominio-de-la-vida', description: 'Se centra en curación, protección y preservación.', featuresByLevel: [{ level: 1, name: 'Discípulo de la vida', description: 'Tus curaciones son más eficaces.' }], imageUrl: null },
      { name: 'Dominio de la Luz', slug: 'dominio-de-la-luz', description: 'Usa luz purificadora, fuego y defensa contra la oscuridad.', featuresByLevel: [{ level: 1, name: 'Destello protector', description: 'Puedes dificultar ataques con luz divina.' }], imageUrl: null },
      { name: 'Dominio de la Naturaleza', slug: 'dominio-de-la-naturaleza', description: 'Vincula fe, mundo salvaje y fuerzas elementales.', featuresByLevel: [{ level: 1, name: 'Acólito de la naturaleza', description: 'Ganas afinidad con saberes y dones naturales.' }], imageUrl: null },
      { name: 'Dominio de la Tempestad', slug: 'dominio-de-la-tempestad', description: 'Invoca trueno, relámpago y castigo implacable.', featuresByLevel: [{ level: 1, name: 'Ira de la tormenta', description: 'Puedes responder con daño de tormenta.' }], imageUrl: null },
      { name: 'Dominio del Engaño', slug: 'dominio-del-engano', description: 'Favorece ilusión, sigilo y confusión táctica.', featuresByLevel: [{ level: 1, name: 'Bendición del embaucador', description: 'Ayudas a un aliado a moverse con sigilo.' }], imageUrl: null },
      { name: 'Dominio de la Guerra', slug: 'dominio-de-la-guerra', description: 'Convierte la devoción en disciplina marcial.', featuresByLevel: [{ level: 1, name: 'Sacerdote de guerra', description: 'Puedes atacar con más presión en combate.' }], imageUrl: null },
    ],
    spellcastingAbility: 'wisdom',
    isSpellcaster: true,
    imageUrl: null,
  },
  {
    name: 'Druida',
    slug: 'druida',
    description: 'Guardián de la naturaleza capaz de lanzar magia primordial y adoptar formas animales.',
    hitDice: '1d8',
    primaryAbilities: ['wisdom'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Bastones', 'Dagas', 'Hondas', 'Jabalinas'],
      tools: ['Kit de herborista'],
      savingThrows: ['intelligence', 'wisdom'],
      skillChoices: skillChoices.druid,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Escudo de madera o arma simple', 'Cimitarra o arma cuerpo a cuerpo simple', 'Armadura de cuero', 'Equipo de explorador', 'Foco druídico'],
    featuresByLevel: [
      { level: 1, name: 'Druídico', description: 'Conoces la lengua secreta de los druidas.' },
      { level: 1, name: 'Lanzamiento de conjuros', description: 'Usas Sabiduría para magia natural.' },
      { level: 2, name: 'Forma salvaje', description: 'Puedes adoptar formas de bestias.' },
      { level: 2, name: 'Círculo druídico', description: 'Eliges una tradición de druidas.' },
    ],
    subclassSelectionLabel: 'Círculo druídico',
    subclassLevel: 2,
    subclasses: [
      { name: 'Círculo de la Tierra', slug: 'circulo-de-la-tierra', description: 'Extrae magia de un terreno espiritual concreto.', featuresByLevel: [{ level: 2, name: 'Recuperación natural', description: 'Recuperas parte de tu magia durante descansos breves.' }], imageUrl: null },
      { name: 'Círculo de la Luna', slug: 'circulo-de-la-luna', description: 'Potencia la transformación animal como herramienta de combate.', featuresByLevel: [{ level: 2, name: 'Forma salvaje de combate', description: 'Usas formas animales con más rapidez y resistencia.' }], imageUrl: null },
    ],
    spellcastingAbility: 'wisdom',
    isSpellcaster: true,
    imageUrl: null,
  },
  {
    name: 'Guerrero',
    slug: 'guerrero',
    description: 'Combatiente experto en armas, armaduras, tácticas y resistencia marcial.',
    hitDice: '1d10',
    primaryAbilities: ['strength', 'dexterity'],
    proficiencies: {
      armor: ['Todas las armaduras', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['strength', 'constitution'],
      skillChoices: skillChoices.fighter,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Cota de malla o armadura de cuero y arco largo', 'Arma marcial y escudo o dos armas marciales', 'Ballesta ligera o hachas de mano', 'Equipo de explorador o de aventurero'],
    featuresByLevel: [
      { level: 1, name: 'Estilo de combate', description: 'Te especializas en una forma de pelear.' },
      { level: 1, name: 'Segundo aliento', description: 'Puedes recuperar fuerzas en mitad del combate.' },
      { level: 2, name: 'Acción súbita', description: 'Puedes realizar un esfuerzo explosivo adicional.' },
      { level: 3, name: 'Arquetipo marcial', description: 'Eliges una vía de maestría marcial.' },
    ],
    subclassSelectionLabel: 'Arquetipo marcial',
    subclassLevel: 3,
    subclasses: [
      { name: 'Campeón', slug: 'campeon', description: 'Especialista directo en potencia física y golpes decisivos.', featuresByLevel: [{ level: 3, name: 'Crítico mejorado', description: 'Tus ataques críticos aparecen con mayor frecuencia.' }], imageUrl: null },
      { name: 'Maestro de Batalla', slug: 'maestro-de-batalla', description: 'Controla el combate con maniobras, precisión y lectura táctica.', featuresByLevel: [{ level: 3, name: 'Maniobras de combate', description: 'Aprendes técnicas que consumen dados de superioridad.' }], imageUrl: null },
      { name: 'Caballero Arcano', slug: 'caballero-arcano', description: 'Combina entrenamiento marcial con magia defensiva y ofensiva.', featuresByLevel: [{ level: 3, name: 'Lanzamiento de conjuros', description: 'Aprendes magia arcana limitada para reforzar tu combate.' }], imageUrl: null },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },
  {
    name: 'Monje',
    slug: 'monje',
    description: 'Artista marcial disciplinado que usa ki para superar límites físicos y espirituales.',
    hitDice: '1d8',
    primaryAbilities: ['dexterity', 'wisdom'],
    proficiencies: {
      armor: [],
      weapons: ['Armas simples', 'Espada corta'],
      tools: ['Herramienta artesanal o instrumento musical'],
      savingThrows: ['strength', 'dexterity'],
      skillChoices: skillChoices.monk,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Espada corta o arma simple', 'Equipo de explorador o aventurero', '10 dardos'],
    featuresByLevel: [
      { level: 1, name: 'Defensa sin armadura', description: 'Tu disciplina mejora tu defensa sin armadura.' },
      { level: 1, name: 'Artes marciales', description: 'Tu cuerpo es un arma precisa.' },
      { level: 2, name: 'Ki', description: 'Gastas energía interior para técnicas especiales.' },
      { level: 3, name: 'Tradición monástica', description: 'Eliges una escuela de entrenamiento espiritual.' },
    ],
    subclassSelectionLabel: 'Tradición monástica',
    subclassLevel: 3,
    subclasses: [
      { name: 'Camino de la Mano Abierta', slug: 'camino-de-la-mano-abierta', description: 'Perfecciona el combate desarmado y el control del cuerpo enemigo.', featuresByLevel: [{ level: 3, name: 'Técnica de la mano abierta', description: 'Tus golpes pueden empujar, derribar o impedir reacciones.' }], imageUrl: null },
      { name: 'Camino de la Sombra', slug: 'camino-de-la-sombra', description: 'Entrena sigilo, oscuridad y movimiento silencioso.', featuresByLevel: [{ level: 3, name: 'Artes sombrías', description: 'Usas ki para crear efectos de ocultación y engaño.' }], imageUrl: null },
      { name: 'Camino de los Cuatro Elementos', slug: 'camino-de-los-cuatro-elementos', description: 'Canaliza ki como fuerza elemental.', featuresByLevel: [{ level: 3, name: 'Discípulo de los elementos', description: 'Aprendes disciplinas elementales alimentadas por ki.' }], imageUrl: null },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },
  {
    name: 'Paladín',
    slug: 'paladin',
    description: 'Guerrero sagrado definido por un juramento, capaz de sanar, proteger y castigar.',
    hitDice: '1d10',
    primaryAbilities: ['strength', 'charisma'],
    proficiencies: {
      armor: ['Todas las armaduras', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['wisdom', 'charisma'],
      skillChoices: skillChoices.paladin,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Arma marcial y escudo o dos armas marciales', 'Cinco jabalinas o arma simple', 'Equipo de sacerdote o explorador', 'Cota de malla', 'Símbolo sagrado'],
    featuresByLevel: [
      { level: 1, name: 'Sentido divino', description: 'Percibes presencias sobrenaturales cercanas.' },
      { level: 1, name: 'Imposición de manos', description: 'Puedes sanar con una reserva de poder sagrado.' },
      { level: 2, name: 'Estilo de combate', description: 'Adoptas una especialización marcial.' },
      { level: 3, name: 'Juramento sagrado', description: 'Defines el voto que guía tu poder.' },
    ],
    subclassSelectionLabel: 'Juramento sagrado',
    subclassLevel: 3,
    subclasses: [
      { name: 'Juramento de Devoción', slug: 'juramento-de-devocion', description: 'Defiende honor, verdad y virtud caballeresca.', featuresByLevel: [{ level: 3, name: 'Canalizar divinidad', description: 'Tu juramento ofrece opciones sagradas de protección y castigo.' }], imageUrl: null },
      { name: 'Juramento de los Ancestros', slug: 'juramento-de-los-ancestros', description: 'Protege la luz, la vida y la belleza del mundo.', featuresByLevel: [{ level: 3, name: 'Canalizar divinidad', description: 'Invocas fuerzas antiguas para contener o expulsar amenazas.' }], imageUrl: null },
      { name: 'Juramento de Venganza', slug: 'juramento-de-venganza', description: 'Persigue a culpables y grandes amenazas con determinación implacable.', featuresByLevel: [{ level: 3, name: 'Canalizar divinidad', description: 'Tu juramento te ayuda a aislar y castigar a un enemigo clave.' }], imageUrl: null },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },
  {
    name: 'Explorador',
    slug: 'explorador',
    description: 'Cazador, rastreador y superviviente experto en terrenos hostiles.',
    hitDice: '1d10',
    primaryAbilities: ['dexterity', 'wisdom'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['strength', 'dexterity'],
      skillChoices: skillChoices.ranger,
      numberOfSkillChoices: 3,
    },
    startingEquipment: ['Armadura de escamas o cuero', 'Dos espadas cortas o dos armas simples', 'Equipo de explorador o aventurero', 'Arco largo y carcaj'],
    featuresByLevel: [
      { level: 1, name: 'Enemigo predilecto', description: 'Te especializas contra ciertos tipos de criaturas.' },
      { level: 1, name: 'Explorador nato', description: 'Dominas el viaje y supervivencia en terrenos concretos.' },
      { level: 2, name: 'Estilo de combate', description: 'Adoptas una técnica marcial.' },
      { level: 3, name: 'Arquetipo de explorador', description: 'Eliges tu enfoque como cazador.' },
    ],
    subclassSelectionLabel: 'Arquetipo de explorador',
    subclassLevel: 3,
    subclasses: [
      { name: 'Cazador', slug: 'cazador', description: 'Especialista en abatir monstruos con técnicas ofensivas adaptables.', featuresByLevel: [{ level: 3, name: 'Presa del cazador', description: 'Eliges una táctica para castigar mejor a tus objetivos.' }], imageUrl: null },
      { name: 'Señor de las Bestias', slug: 'senor-de-las-bestias', description: 'Combate junto a un compañero animal entrenado.', featuresByLevel: [{ level: 3, name: 'Compañero del explorador', description: 'Obtienes una bestia aliada que actúa contigo.' }], imageUrl: null },
    ],
    spellcastingAbility: 'wisdom',
    isSpellcaster: true,
    imageUrl: null,
  },
  {
    name: 'Pícaro',
    slug: 'picaro',
    description: 'Especialista en precisión, sigilo, engaño y resolución creativa de problemas.',
    hitDice: '1d8',
    primaryAbilities: ['dexterity'],
    proficiencies: {
      armor: ['Armadura ligera'],
      weapons: ['Armas simples', 'Ballesta de mano', 'Espada larga', 'Estoque', 'Espada corta'],
      tools: ['Herramientas de ladrón'],
      savingThrows: ['dexterity', 'intelligence'],
      skillChoices: skillChoices.rogue,
      numberOfSkillChoices: 4,
    },
    startingEquipment: ['Estoque o espada corta', 'Arco corto o espada corta', 'Equipo de ladrón, aventurero o explorador', 'Armadura de cuero', 'Dagas', 'Herramientas de ladrón'],
    featuresByLevel: [
      { level: 1, name: 'Pericia', description: 'Doblas tu competencia en áreas concretas.' },
      { level: 1, name: 'Ataque furtivo', description: 'Golpeas puntos vulnerables cuando tienes ventaja táctica.' },
      { level: 2, name: 'Acción astuta', description: 'Te mueves, ocultas o reposicionas con rapidez.' },
      { level: 3, name: 'Arquetipo pícaro', description: 'Eliges tu estilo criminal, técnico o arcano.' },
    ],
    subclassSelectionLabel: 'Arquetipo pícaro',
    subclassLevel: 3,
    subclasses: [
      { name: 'Ladrón', slug: 'ladron', description: 'Experto en infiltración, movilidad y uso ingenioso de objetos.', featuresByLevel: [{ level: 3, name: 'Manos rápidas', description: 'Interactúas con objetos y herramientas con gran rapidez.' }], imageUrl: null },
      { name: 'Asesino', slug: 'asesino', description: 'Especialista en emboscadas, identidades falsas y golpes letales.', featuresByLevel: [{ level: 3, name: 'Asesinar', description: 'Tus emboscadas son especialmente peligrosas.' }], imageUrl: null },
      { name: 'Embaucador Arcano', slug: 'embaucador-arcano', description: 'Mezcla sigilo y magia de ilusión o encantamiento.', featuresByLevel: [{ level: 3, name: 'Lanzamiento de conjuros', description: 'Aprendes magia arcana útil para engañar y controlar.' }], imageUrl: null },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },
  {
    name: 'Hechicero',
    slug: 'hechicero',
    description: 'Lanzador de conjuros cuya magia nace de un poder interior innato.',
    hitDice: '1d6',
    primaryAbilities: ['charisma'],
    proficiencies: {
      armor: [],
      weapons: ['Dagas', 'Dardos', 'Hondas', 'Bastones', 'Ballestas ligeras'],
      tools: [],
      savingThrows: ['constitution', 'charisma'],
      skillChoices: skillChoices.sorcerer,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Ballesta ligera o arma simple', 'Bolsa de componentes o foco arcano', 'Equipo de explorador o aventurero', 'Dos dagas'],
    featuresByLevel: [
      { level: 1, name: 'Lanzamiento de conjuros', description: 'Usas Carisma para moldear magia innata.' },
      { level: 1, name: 'Origen sobrenatural', description: 'Tu fuente de poder define tus dones.' },
      { level: 2, name: 'Fuente de magia', description: 'Obtienes puntos de hechicería para alterar tu magia.' },
      { level: 3, name: 'Metamagia', description: 'Modificas tus conjuros con técnicas únicas.' },
    ],
    subclassSelectionLabel: 'Origen sobrenatural',
    subclassLevel: 1,
    subclasses: [
      { name: 'Linaje Dracónico', slug: 'linaje-draconico', description: 'Tu magia procede de una herencia vinculada a dragones.', featuresByLevel: [{ level: 1, name: 'Antepasado dragón', description: 'Eliges un tipo de dragón que marca tu magia.' }], imageUrl: null },
      { name: 'Magia Salvaje', slug: 'magia-salvaje', description: 'Tu poder surge de fuerzas caóticas difíciles de contener.', featuresByLevel: [{ level: 1, name: 'Oleada de magia salvaje', description: 'Tu magia puede desatar efectos imprevisibles.' }], imageUrl: null },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },
  {
    name: 'Brujo',
    slug: 'brujo',
    description: 'Usuario de magia obtenida mediante pacto con una entidad poderosa.',
    hitDice: '1d8',
    primaryAbilities: ['charisma'],
    proficiencies: {
      armor: ['Armadura ligera'],
      weapons: ['Armas simples'],
      tools: [],
      savingThrows: ['wisdom', 'charisma'],
      skillChoices: skillChoices.warlock,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Ballesta ligera o arma simple', 'Bolsa de componentes o foco arcano', 'Equipo de erudito o aventurero', 'Armadura de cuero', 'Arma simple', 'Dagas'],
    featuresByLevel: [
      { level: 1, name: 'Pacto sobrenatural', description: 'Tu patrón define parte de tu magia y enfoque.' },
      { level: 1, name: 'Magia de pacto', description: 'Lanzas conjuros mediante pactos de poder renovable.' },
      { level: 2, name: 'Invocaciones sobrenaturales', description: 'Aprendes dones especiales de tu patrón.' },
      { level: 3, name: 'Don del pacto', description: 'Recibes un beneficio mayor de tu acuerdo.' },
    ],
    subclassSelectionLabel: 'Patrón sobrenatural',
    subclassLevel: 1,
    subclasses: [
      { name: 'Archihada', slug: 'archihada', description: 'Tu patrón procede de los poderes feéricos más antiguos.', featuresByLevel: [{ level: 1, name: 'Presencia feérica', description: 'Puedes envolver criaturas en encanto o temor.' }], imageUrl: null },
      { name: 'Infernal', slug: 'infernal', description: 'Tu pacto te vincula con un poder de los planos inferiores.', featuresByLevel: [{ level: 1, name: 'Bendición oscura', description: 'Ganas vitalidad temporal al derrotar enemigos.' }], imageUrl: null },
      { name: 'Gran Antiguo', slug: 'gran-antiguo', description: 'Tu patrón es una entidad cósmica ajena a la realidad común.', featuresByLevel: [{ level: 1, name: 'Mente despierta', description: 'Puedes comunicar ideas directamente a otras mentes.' }], imageUrl: null },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },
  {
    name: 'Mago',
    slug: 'mago',
    description: 'Erudito arcano que aprende, prepara y perfecciona magia mediante estudio.',
    hitDice: '1d6',
    primaryAbilities: ['intelligence'],
    proficiencies: {
      armor: [],
      weapons: ['Dagas', 'Dardos', 'Hondas', 'Bastones', 'Ballestas ligeras'],
      tools: [],
      savingThrows: ['intelligence', 'wisdom'],
      skillChoices: skillChoices.wizard,
      numberOfSkillChoices: 2,
    },
    startingEquipment: ['Bastón o daga', 'Bolsa de componentes o foco arcano', 'Equipo de erudito o explorador', 'Libro de conjuros'],
    featuresByLevel: [
      { level: 1, name: 'Lanzamiento de conjuros', description: 'Usas Inteligencia y un libro de conjuros para preparar magia.' },
      { level: 1, name: 'Recuperación arcana', description: 'Recuperas parte de tu energía mágica durante descansos.' },
      { level: 2, name: 'Tradición arcana', description: 'Eliges una escuela o método de estudio mágico.' },
    ],
    subclassSelectionLabel: 'Tradición arcana',
    subclassLevel: 2,
    subclasses: [
      { name: 'Escuela de Abjuración', slug: 'escuela-de-abjuracion', description: 'Especializada en protección, barreras y anulación.', featuresByLevel: [{ level: 2, name: 'Custodia arcana', description: 'Tu magia protectora crea una defensa persistente.' }], imageUrl: null },
      { name: 'Escuela de Conjuración', slug: 'escuela-de-conjuracion', description: 'Domina invocación, transporte y creación mágica.', featuresByLevel: [{ level: 2, name: 'Conjuración menor', description: 'Puedes crear pequeños objetos temporales.' }], imageUrl: null },
      { name: 'Escuela de Adivinación', slug: 'escuela-de-adivinacion', description: 'Lee posibilidades, augurios e información oculta.', featuresByLevel: [{ level: 2, name: 'Portento', description: 'Presientes resultados que luego puedes imponer.' }], imageUrl: null },
      { name: 'Escuela de Encantamiento', slug: 'escuela-de-encantamiento', description: 'Influye en emociones, atención y voluntad.', featuresByLevel: [{ level: 2, name: 'Mirada hipnótica', description: 'Puedes embelesar temporalmente a una criatura.' }], imageUrl: null },
      { name: 'Escuela de Evocación', slug: 'escuela-de-evocacion', description: 'Modela energía destructiva con precisión académica.', featuresByLevel: [{ level: 2, name: 'Esculpir conjuros', description: 'Proteges aliados dentro de tus explosiones mágicas.' }], imageUrl: null },
      { name: 'Escuela de Ilusión', slug: 'escuela-de-ilusion', description: 'Crea engaños sensoriales y realidades aparentes.', featuresByLevel: [{ level: 2, name: 'Ilusión menor mejorada', description: 'Tu dominio mejora trucos ilusorios básicos.' }], imageUrl: null },
      { name: 'Escuela de Nigromancia', slug: 'escuela-de-nigromancia', description: 'Estudia vida, muerte y energía necrótica.', featuresByLevel: [{ level: 2, name: 'Cosecha sombría', description: 'Recuperas vitalidad al abatir criaturas con magia.' }], imageUrl: null },
      { name: 'Escuela de Transmutación', slug: 'escuela-de-transmutacion', description: 'Altera materia, forma y propiedades físicas.', featuresByLevel: [{ level: 2, name: 'Alquimia menor', description: 'Puedes transformar temporalmente materiales simples.' }], imageUrl: null },
    ],
    spellcastingAbility: 'intelligence',
    isSpellcaster: true,
    imageUrl: null,
  },
];

export const classesSeed = rawClassesSeed.map((classSeed) => ({
  ...classSeed,
  startingEquipmentChoices: equipmentChoices[classSeed.slug] || [],
}));
