export const classesSeed = [
  {
    name: 'Bárbaro',
    slug: 'barbaro',
    description:
      'Guerrero salvaje movido por una furia primitiva, resistente en combate y devastador cuerpo a cuerpo.',
    hitDice: '1d12',
    primaryAbilities: ['strength', 'constitution'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['strength', 'constitution'],
      skillChoices: [
        'Atletismo',
        'Intimidación',
        'Naturaleza',
        'Percepción',
        'Supervivencia',
        'Trato con Animales',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Gran hacha o cualquier arma marcial cuerpo a cuerpo',
      'Dos hachas de mano o cualquier arma simple',
      'Equipo de explorador',
      'Cuatro jabalinas',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Furia',
        description:
          'Puedes entrar en furia para aumentar tus capacidades físicas.',
      },
      {
        level: 1,
        name: 'Defensa sin armadura',
        description: 'Tu CA puede calcularse sin armadura usando DEX y CON.',
      },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },

  {
    name: 'Bardo',
    slug: 'bardo',
    description:
      'Artista, erudito y lanzador de conjuros versátil capaz de inspirar aliados.',
    hitDice: '1d8',
    primaryAbilities: ['charisma'],
    proficiencies: {
      armor: ['Armadura ligera'],
      weapons: [
        'Armas simples',
        'Ballesta de mano',
        'Espada larga',
        'Estoque',
        'Espada corta',
      ],
      tools: ['Tres instrumentos musicales'],
      savingThrows: ['dexterity', 'charisma'],
      skillChoices: [
        'Acrobacias',
        'Arcanos',
        'Atletismo',
        'Engaño',
        'Historia',
        'Interpretación',
        'Intimidación',
        'Investigación',
        'Juego de Manos',
        'Medicina',
        'Naturaleza',
        'Percepción',
        'Perspicacia',
        'Persuasión',
        'Religión',
        'Sigilo',
        'Supervivencia',
        'Trato con Animales',
      ],
      numberOfSkillChoices: 3,
    },
    startingEquipment: [
      'Estoque, espada larga o arma simple',
      'Equipo diplomático o equipo de artista',
      'Laúd o instrumento musical',
      'Armadura de cuero y daga',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Inspiración bárdica',
        description: 'Puedes inspirar aliados con dados de inspiración.',
      },
      {
        level: 1,
        name: 'Lanzamiento de conjuros',
        description: 'Acceso a magia basada en Carisma.',
      },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },

  {
    name: 'Clérigo',
    slug: 'clerigo',
    description: 'Canalizador de poder divino al servicio de una deidad.',
    hitDice: '1d8',
    primaryAbilities: ['wisdom'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Armas simples'],
      tools: [],
      savingThrows: ['wisdom', 'charisma'],
      skillChoices: [
        'Historia',
        'Intimidación',
        'Medicina',
        'Perspicacia',
        'Persuasión',
        'Religión',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Maza o martillo de guerra',
      'Armadura de escamas o cuero',
      'Ballesta ligera o arma simple',
      'Símbolo sagrado',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Lanzamiento de conjuros',
        description: 'Magia divina basada en Sabiduría.',
      },
      {
        level: 1,
        name: 'Dominio divino',
        description: 'Selecciona un dominio relacionado con tu deidad.',
      },
    ],
    spellcastingAbility: 'wisdom',
    isSpellcaster: true,
    imageUrl: null,
  },

  {
    name: 'Druida',
    slug: 'druida',
    description:
      'Guardián de la naturaleza capaz de transformarse y lanzar magia natural.',
    hitDice: '1d8',
    primaryAbilities: ['wisdom'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Bastones', 'Dagas', 'Hondas', 'Jabalinas'],
      tools: ['Kit de herborista'],
      savingThrows: ['intelligence', 'wisdom'],
      skillChoices: [
        'Arcanos',
        'Medicina',
        'Naturaleza',
        'Percepción',
        'Religión',
        'Supervivencia',
        'Trato con Animales',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Escudo de madera',
      'Hoz o arma simple',
      'Equipo de explorador',
      'Foco druídico',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Druídico',
        description: 'Conoces el idioma secreto de los druidas.',
      },
      {
        level: 1,
        name: 'Lanzamiento de conjuros',
        description: 'Magia natural basada en Sabiduría.',
      },
    ],
    spellcastingAbility: 'wisdom',
    isSpellcaster: true,
    imageUrl: null,
  },

  {
    name: 'Guerrero',
    slug: 'guerrero',
    description: 'Combatiente experto en armas y tácticas.',
    hitDice: '1d10',
    primaryAbilities: ['strength', 'dexterity'],
    proficiencies: {
      armor: ['Todas las armaduras', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['strength', 'constitution'],
      skillChoices: [
        'Acrobacias',
        'Atletismo',
        'Historia',
        'Intimidación',
        'Percepción',
        'Perspicacia',
        'Supervivencia',
        'Trato con Animales',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Cota de malla',
      'Escudo y arma marcial',
      'Ballesta ligera',
      'Equipo de explorador',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Estilo de combate',
        description: 'Especialización marcial concreta.',
      },
      {
        level: 1,
        name: 'Segundo aliento',
        description: 'Recuperas puntos de golpe.',
      },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },

  {
    name: 'Monje',
    slug: 'monje',
    description:
      'Maestro marcial que utiliza ki para realizar proezas sobrenaturales.',
    hitDice: '1d8',
    primaryAbilities: ['dexterity', 'wisdom'],
    proficiencies: {
      armor: [],
      weapons: ['Armas simples', 'Espada corta'],
      tools: ['Herramienta artesanal o instrumento musical'],
      savingThrows: ['strength', 'dexterity'],
      skillChoices: [
        'Acrobacias',
        'Atletismo',
        'Historia',
        'Perspicacia',
        'Religión',
        'Sigilo',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Espada corta o arma simple',
      'Equipo de explorador',
      '10 dardos',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Defensa sin armadura',
        description: 'CA basada en DEX y WIS.',
      },
      {
        level: 1,
        name: 'Artes marciales',
        description: 'Combate desarmado especializado.',
      },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },

  {
    name: 'Paladín',
    slug: 'paladin',
    description: 'Guerrero sagrado impulsado por un juramento.',
    hitDice: '1d10',
    primaryAbilities: ['strength', 'charisma'],
    proficiencies: {
      armor: ['Todas las armaduras', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['wisdom', 'charisma'],
      skillChoices: [
        'Atletismo',
        'Intimidación',
        'Medicina',
        'Perspicacia',
        'Persuasión',
        'Religión',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Arma marcial y escudo',
      'Cinco jabalinas',
      'Símbolo sagrado',
      'Equipo de sacerdote',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Sentido divino',
        description: 'Detectas presencias sobrenaturales.',
      },
      {
        level: 1,
        name: 'Manos curativas',
        description: 'Reservorio de curación.',
      },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },

  {
    name: 'Explorador',
    slug: 'explorador',
    description: 'Cazador y superviviente experto en rastreo y naturaleza.',
    hitDice: '1d10',
    primaryAbilities: ['dexterity', 'wisdom'],
    proficiencies: {
      armor: ['Armadura ligera', 'Armadura media', 'Escudos'],
      weapons: ['Armas simples', 'Armas marciales'],
      tools: [],
      savingThrows: ['strength', 'dexterity'],
      skillChoices: [
        'Atletismo',
        'Investigación',
        'Naturaleza',
        'Percepción',
        'Sigilo',
        'Supervivencia',
        'Trato con Animales',
      ],
      numberOfSkillChoices: 3,
    },
    startingEquipment: [
      'Armadura de cuero',
      'Dos espadas cortas',
      'Arco largo',
      'Equipo de explorador',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Enemigo predilecto',
        description: 'Especialización contra ciertos enemigos.',
      },
      {
        level: 1,
        name: 'Explorador nato',
        description: 'Ventajas en supervivencia y viaje.',
      },
    ],
    spellcastingAbility: 'wisdom',
    isSpellcaster: true,
    imageUrl: null,
  },

  {
    name: 'Pícaro',
    slug: 'picaro',
    description: 'Especialista en sigilo, precisión y habilidades.',
    hitDice: '1d8',
    primaryAbilities: ['dexterity'],
    proficiencies: {
      armor: ['Armadura ligera'],
      weapons: [
        'Armas simples',
        'Ballesta de mano',
        'Espada larga',
        'Estoque',
        'Espada corta',
      ],
      tools: ['Herramientas de ladrón'],
      savingThrows: ['dexterity', 'intelligence'],
      skillChoices: [
        'Acrobacias',
        'Atletismo',
        'Engaño',
        'Interpretación',
        'Intimidación',
        'Investigación',
        'Juego de Manos',
        'Percepción',
        'Perspicacia',
        'Persuasión',
        'Sigilo',
      ],
      numberOfSkillChoices: 4,
    },
    startingEquipment: [
      'Estoque o espada corta',
      'Arco corto y carcaj',
      'Herramientas de ladrón',
      'Equipo de ladrón',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Ataque furtivo',
        description: 'Daño extra bajo ciertas condiciones.',
      },
      {
        level: 1,
        name: 'Pericia',
        description: 'Doblas competencia en habilidades concretas.',
      },
    ],
    isSpellcaster: false,
    imageUrl: null,
  },

  {
    name: 'Hechicero',
    slug: 'hechicero',
    description: 'Lanzador de conjuros con magia innata.',
    hitDice: '1d6',
    primaryAbilities: ['charisma'],
    proficiencies: {
      armor: [],
      weapons: ['Dagas', 'Dardos', 'Hondas', 'Ballestas ligeras'],
      tools: [],
      savingThrows: ['constitution', 'charisma'],
      skillChoices: [
        'Arcanos',
        'Engaño',
        'Intimidación',
        'Perspicacia',
        'Persuasión',
        'Religión',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Ballesta ligera',
      'Foco arcano',
      'Equipo de explorador',
      'Dos dagas',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Lanzamiento de conjuros',
        description: 'Magia innata basada en Carisma.',
      },
      {
        level: 1,
        name: 'Origen sobrenatural',
        description: 'Fuente de poder mágico.',
      },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },

  {
    name: 'Brujo',
    slug: 'brujo',
    description: 'Usuario de magia derivada de pactos sobrenaturales.',
    hitDice: '1d8',
    primaryAbilities: ['charisma'],
    proficiencies: {
      armor: ['Armadura ligera'],
      weapons: ['Armas simples'],
      tools: [],
      savingThrows: ['wisdom', 'charisma'],
      skillChoices: [
        'Arcanos',
        'Engaño',
        'Historia',
        'Intimidación',
        'Investigación',
        'Naturaleza',
        'Religión',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Ballesta ligera',
      'Componente arcano',
      'Arma simple',
      'Armadura de cuero',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Pacto sobrenatural',
        description: 'Tu magia proviene de una entidad poderosa.',
      },
      {
        level: 1,
        name: 'Magia de pacto',
        description: 'Sistema especial de slots de conjuro.',
      },
    ],
    spellcastingAbility: 'charisma',
    isSpellcaster: true,
    imageUrl: null,
  },

  {
    name: 'Mago',
    slug: 'mago',
    description: 'Erudito arcano especializado en el estudio de la magia.',
    hitDice: '1d6',
    primaryAbilities: ['intelligence'],
    proficiencies: {
      armor: [],
      weapons: ['Dagas', 'Dardos', 'Hondas', 'Bastones', 'Ballestas ligeras'],
      tools: [],
      savingThrows: ['intelligence', 'wisdom'],
      skillChoices: [
        'Arcanos',
        'Historia',
        'Investigación',
        'Medicina',
        'Perspicacia',
        'Religión',
      ],
      numberOfSkillChoices: 2,
    },
    startingEquipment: [
      'Bastón o daga',
      'Libro de conjuros',
      'Foco arcano',
      'Equipo de erudito',
    ],
    featuresByLevel: [
      {
        level: 1,
        name: 'Lanzamiento de conjuros',
        description: 'Magia arcana basada en Inteligencia.',
      },
      {
        level: 1,
        name: 'Recuperación arcana',
        description: 'Recuperas slots de conjuro.',
      },
    ],
    spellcastingAbility: 'intelligence',
    isSpellcaster: true,
    imageUrl: null,
  },
];
